const input=document.getElementById('fileInput');const upload=document.getElementById('uploadBtn');const fileName=document.getElementById('fileName');const workspace=document.getElementById('workspace');const result=document.getElementById('result');const canvas=document.getElementById('chartCanvas');const ctx=canvas.getContext('2d');const direction=document.getElementById('direction');const saveBtn=document.getElementById('saveBtn');let image=null;let originalName='chart';

upload.onclick=()=>input.click();
input.onchange=()=>{const file=input.files?.[0];if(!file)return;originalName=file.name.replace(/\.[^.]+$/,'');fileName.textContent=file.name;const reader=new FileReader();reader.onload=e=>{image=new Image();image.onload=()=>{workspace.classList.remove('hidden');result.classList.add('hidden');drawBase();};image.src=e.target.result};reader.readAsDataURL(file)};
function fit(){const max=window.innerWidth*.94;const scale=Math.min(1,max/image.width);canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);return scale}
function drawBase(){fit();ctx.drawImage(image,0,0,canvas.width,canvas.height)}
function luminance(r,g,b){return .2126*r+.7152*g+.0722*b}
function analyzePixels(){const data=ctx.getImageData(0,0,canvas.width,canvas.height).data;let green=0,red=0,dark=0,light=0;for(let i=0;i<data.length;i+=4){const r=data[i],g=data[i+1],b=data[i+2],l=luminance(r,g,b);if(g>r*1.12&&g>b*1.08)green++;if(r>g*1.12&&r>b*1.08)red++;if(l<75)dark++;if(l>210)light++}return{green,red,dark,light}}
function drawLine(y,label,kind){const x=canvas.width*.04;const w=canvas.width*.92;ctx.save();ctx.lineWidth=Math.max(2,canvas.width/500);ctx.setLineDash([12,8]);ctx.strokeStyle=kind==='entry'?'#3778ff':kind==='tp'?'#2d9b64':'#d64d4d';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+w,y);ctx.stroke();ctx.setLineDash([]);ctx.font='700 13px system-ui';ctx.fillStyle=ctx.strokeStyle;ctx.fillText(label,x+8,Math.max(18,y-8));ctx.restore()}
function analyze(){if(!image)return;drawBase();const stats=analyzePixels();let mode=direction.value;if(mode==='auto')mode=stats.green>=stats.red?'bullish':'bearish';const h=canvas.height;let entry,tp,sl;if(mode==='bullish'){entry=h*.54;sl=h*.73;tp=h*.24}else{entry=h*.46;sl=h*.27;tp=h*.76}drawLine(entry,'ENTRY','entry');drawLine(tp,'TP','tp');drawLine(sl,'SL','sl');document.getElementById('setupTitle').textContent=mode==='bullish'?'Bullish structure':'Bearish structure';const total=stats.green+stats.red+1;const bias=Math.round(55+Math.min(35,Math.abs(stats.green-stats.red)/total*100));document.getElementById('confidence').textContent=`Structure confidence ${bias}%`;document.getElementById('reasoning').textContent=mode==='bullish'?'The overlay prioritises visible bullish pressure, structure continuation and a pullback entry. TP is placed toward the upper range and SL beyond the lower invalidation area.':'The overlay prioritises visible bearish pressure, structure continuation and a pullback entry. TP is placed toward the lower range and SL beyond the upper invalidation area.';result.classList.remove('hidden');result.scrollIntoView({behavior:'smooth',block:'start'})}

document.getElementById('analyzeBtn').onclick=analyze;
document.getElementById('resetBtn').onclick=()=>{if(image){drawBase();result.classList.add('hidden')}};

async function saveAnnotatedChart(){if(!image)return;const filename=`${originalName}-analysis.png`;canvas.toBlob(async blob=>{if(!blob)return;const file=new File([blob],filename,{type:'image/png'});try{if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({title:'Chart Analysis',text:'Annotated chart analysis',files:[file]});return}}catch(err){if(err?.name==='AbortError')return}const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)},'image/png')}
saveBtn.onclick=saveAnnotatedChart;
saveBtn.textContent='Save / Share chart';
window.onresize=()=>{if(image&&!result.classList.contains('hidden'))analyze();else if(image)drawBase()};
